### ISSUE TITLE
How to build proper iPad version?

### ISSUE THREAD

**Issue by INDIGI-CO-UK** [pguyot/Einstein#12]
Guys!

I'm not programmer and compilation is dark magic for me, but I would like to have Newton OS on my iPad Mini (1g). How can I do this?

Cheers,
Pawel

**Comment by panicsteve** [comment]
Hi Pawel,

It's unfortunately a fairly complicated process.  We cannot provide an easy installer because we are not authorized to distribute the required Newton ROM file, and Apple will not permit Einstein in the App Store.  The only option that leaves is to compile and install your own copy.

At a minimum you will need:

- Xcode
- An Apple Developer account
- A ROM dump from an actual Newton 2x00 device

Also I think you might not be happy with the performance of Einstein on a first-generation iPad Mini.  At this point in time it is more of an exciting proof of concept.

If you'd still like to try it, there are some high-level instructions on the wiki:

https://github.com/pguyot/Einstein/wiki/Build-Instructions

If you get stuck, open another issue and we might be able to help!
