### ISSUE TITLE
Using NewtTest 1.1i outside of the Einstein REX

### ISSUE THREAD

**Issue by splorp** [pguyot/Einstein#34]
Does anyone know if the updated version of Frank’s NewtTest package currently installed as part of the Einstein REX will work on a normal Newton device.

(I guess I could download it and give it a try.)

**Comment by FrankFromPdaSoft** [comment]
It will work, since it was developed on a Newton. However, this version wasn’t officially published for a reason. This is because more pressing issues prevented me from testing the new stuff as thoroughly as I normally do on different Newton models.

 

Von: Grant Hutchinson [mailto:notifications@github.com] 
Gesendet: Sonntag, 29. Oktober 2017 17:48
An: pguyot/Einstein
Cc: Subscribed
Betreff: [pguyot/Einstein] Using NewtTest 1.1i outside of the Einstein REX (#34)

 

Does anyone know if the updated version of Frank’s NewtTest package currently installed as part of the Einstein REX will work on a normal Newton device.

(I guess I could download it and give it a try.)

**Comment by splorp** [comment]
Thanks, Frank.

Do you have a series of tests that you use to check “the new stuff”? I’d be happy to run some tests on my pile of Newts.

**Comment by FrankFromPdaSoft** [comment]
The problem is that the “new stuff” is a couple of years old. I simply do not find the time to work on NewtTest at the moment. 

 

Von: Grant Hutchinson [mailto:notifications@github.com] 
Gesendet: Dienstag, 28. November 2017 17:48
An: pguyot/Einstein
Cc: Frank Gruendel; Comment
Betreff: Re: [pguyot/Einstein] Using NewtTest 1.1i outside of the Einstein REX (#34)

 

Thanks, Frank.

Do you have a series of tests that you use to check “the new stuff”? I’d be happy to run some tests on my pile of Newts.

**Comment by MatthiasWM** [comment]
Frank, Grant, if I may, I will close this issue by the end of the month, as it is not Einstein dev related, and I know that yu guys are in direct contact anyway. More on NewtTest can be found on Franks website:

http://www.pda-soft.de/newttest.html

**Comment by splorp** [comment]
Agreed.
