### ISSUE TITLE
Removal of Eclipse Android build option

### ISSUE THREAD

**Issue by MatthiasWM** [pguyot/Einstein#51]
## Basic Information

Android developers used to write code in Eclipse. A few years ago, this IDE was officially replaced by AndroidStudio. The EinsteinStudio build option is now at least at the same level as Eclipse/

## Description of issue

IMHO There is no need to have two build environments for a single platform (not considering command line build options) 

## Request for comment

Does anyone see any reason to keep the Eclipse project around? If not, I would like to remove it from the repo by the end of May.

**Comment by FrankFromPdaSoft** [comment]
I made the Android version with Android Studio when it came out. It works OK, but not as fluently and effortlessly as it was under Eclipse. However, since (I think) Eclipse is not longer supported by the makers of Android,  removing the Eclipse project is probably a good idea.

 

Von: MatthiasWM [mailto:notifications@github.com] 
Gesendet: Freitag, 18. Mai 2018 09:53
An: pguyot/Einstein
Cc: Subscribed
Betreff: [pguyot/Einstein] Removal of Eclipse Android build option (#51)

 


Basic Information


Android developers used to write code in Eclipse. A few years ago, this IDE was officially replaced by AndroidStudio. The EinsteinStudio build option is now at least at the same level as Eclipse/


Description of issue


IMHO There is no need to have two build environments for a single platform (not considering command line build options)


Request for comment


Does anyone see any reason to keep the Eclipse project around? If not, I would like to remove it from the repo by the end of May.

**Comment by MatthiasWM** [comment]
Removed Android Eclipse support.
