### ISSUE TITLE
Covert Mac line endings in source files

### ISSUE THREAD

**Issue by ekoeppen** [pguyot/Einstein#88]
It seems that the NCT tools can handle DOS formatted files (`CR` + `LF`) in addition to files with Mac line endings (`CR`). Testing this by converting the files in `Drivers` and running `make` using `mosrun` was successful.

This allows for a better `git` workflow, as currently, diffs for Mac formatted files are not working on e.g. Linux.

**Comment by pguyot** [comment]
I've been working on a Rex replacement to simply drop mosrun and MPW tools to build the Rex with gcc, binutils and ELFtoPKG. So we'll be able to drop CR line ending everywhere except with NewtonScript code that is supposed to be compiled with NTK.

**Comment by pguyot** [comment]
For the record, the current issue is related to NTHelp10.pkg package which is generated by BookMaker which seems to generate a faulty frame that DCL chokes on.

At part offset 00018A78 (package offset 00018B78), there is a frame, with a map at 000188F8 (package: 000189F8) which is an array of class 'Array instead of an integer. @MatthiasWM 's decompiler doesn't seem to care.

**Comment by pguyot** [comment]
Relevant commit: https://github.com/pguyot/DCL/commit/9171d8839c1320e6250e70b623636f21f18f3161

**Comment by ekoeppen** [comment]
Of course! That's the right approach. I'll happily wait for that :)

**Comment by pguyot** [comment]
Fixed in 18c0f26
